<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 5 Linear Regression - Theory | Data Analysis with R for Social Scientists</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content=" 5 Linear Regression - Theory | Data Analysis with R for Social Scientists" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="jaspertjaden/DataAnalysisR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 5 Linear Regression - Theory | Data Analysis with R for Social Scientists" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Jakob Tures &amp; Jasper Tjaden" />


<meta name="date" content="2023-08-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="eda-2.html"/>
<link rel="next" href="lin-a.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Analysis with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> url: your book url like https://bookdown.org/yihui/bookdown</a></li>
<li class="chapter" data-level="2" data-path="intro-sem.html"><a href="intro-sem.html"><i class="fa fa-check"></i><b>2</b> Introduction to Seminar</a></li>
<li class="chapter" data-level="3" data-path="eda-1.html"><a href="eda-1.html"><i class="fa fa-check"></i><b>3</b> Exloratory Data Analysis - I</a>
<ul>
<li class="chapter" data-level="3.1" data-path="eda-1.html"><a href="eda-1.html#objectives"><i class="fa fa-check"></i><b>3.1</b> Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="eda-1.html"><a href="eda-1.html#r-functions-covered-this-week"><i class="fa fa-check"></i><b>3.2</b> R functions covered this week</a></li>
<li class="chapter" data-level="3.3" data-path="eda-1.html"><a href="eda-1.html#why-is-eda-so-important"><i class="fa fa-check"></i><b>3.3</b> Why is EDA so important?</a></li>
<li class="chapter" data-level="3.4" data-path="eda-1.html"><a href="eda-1.html#importing-data-into-r"><i class="fa fa-check"></i><b>3.4</b> Importing data into R</a></li>
<li class="chapter" data-level="3.5" data-path="eda-1.html"><a href="eda-1.html#import-data-into-r"><i class="fa fa-check"></i><b>3.5</b> Import data into R</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="eda-1.html"><a href="eda-1.html#from-csv"><i class="fa fa-check"></i><b>3.5.1</b> From CSV</a></li>
<li class="chapter" data-level="3.5.2" data-path="eda-1.html"><a href="eda-1.html#from-stata-.dta"><i class="fa fa-check"></i><b>3.5.2</b> from Stata (.dta)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="eda-1.html"><a href="eda-1.html#change-dataset"><i class="fa fa-check"></i><b>3.6</b> Change dataset</a></li>
<li class="chapter" data-level="3.7" data-path="eda-1.html"><a href="eda-1.html#change-variables"><i class="fa fa-check"></i><b>3.7</b> change variables</a></li>
<li class="chapter" data-level="3.8" data-path="eda-1.html"><a href="eda-1.html#combine-with-other-data"><i class="fa fa-check"></i><b>3.8</b> combine with other data</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="eda-1.html"><a href="eda-1.html#explore-individual-variables"><i class="fa fa-check"></i><b>3.8.1</b> explore individual variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="eda-2.html"><a href="eda-2.html"><i class="fa fa-check"></i><b>4</b> Exploratory Data Analysis - II</a>
<ul>
<li class="chapter" data-level="4.1" data-path="eda-2.html"><a href="eda-2.html#markdown-introduction"><i class="fa fa-check"></i><b>4.1</b> Markdown Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="eda-2.html"><a href="eda-2.html#applying-edawvsown-data"><i class="fa fa-check"></i><b>4.2</b> Applying EDA(WVS/own data)</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="eda-2.html"><a href="eda-2.html#exercise---1"><i class="fa fa-check"></i><b>4.2.1</b> Exercise - 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lin-t.html"><a href="lin-t.html"><i class="fa fa-check"></i><b>5</b> Linear Regression - Theory</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lin-t.html"><a href="lin-t.html#what-is-linear-regression"><i class="fa fa-check"></i><b>5.1</b> What is Linear Regression</a></li>
<li class="chapter" data-level="5.2" data-path="lin-t.html"><a href="lin-t.html#examplary-research-question-data"><i class="fa fa-check"></i><b>5.2</b> Examplary research question &amp; data</a></li>
<li class="chapter" data-level="5.3" data-path="lin-t.html"><a href="lin-t.html#simple-linear-regression"><i class="fa fa-check"></i><b>5.3</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="lin-t.html"><a href="lin-t.html#regression-formula"><i class="fa fa-check"></i><b>5.3.1</b> Regression Formula</a></li>
<li class="chapter" data-level="5.3.2" data-path="lin-t.html"><a href="lin-t.html#regressing-grade-on-hours"><i class="fa fa-check"></i><b>5.3.2</b> Regressing <code>grade</code> on <code>hours</code></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="lin-t.html"><a href="lin-t.html#multiple-linear-regression"><i class="fa fa-check"></i><b>5.4</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="lin-t.html"><a href="lin-t.html#adding-additional-variables"><i class="fa fa-check"></i><b>5.4.1</b> Adding additional variables</a></li>
<li class="chapter" data-level="5.4.2" data-path="lin-t.html"><a href="lin-t.html#adding-dummy-variables"><i class="fa fa-check"></i><b>5.4.2</b> Adding dummy variables</a></li>
<li class="chapter" data-level="5.4.3" data-path="lin-t.html"><a href="lin-t.html#adding-categorical-variables"><i class="fa fa-check"></i><b>5.4.3</b> Adding categorical variables</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="lin-t.html"><a href="lin-t.html#returning-to-our-research-question"><i class="fa fa-check"></i><b>5.5</b> Returning to our research question</a></li>
<li class="chapter" data-level="5.6" data-path="lin-t.html"><a href="lin-t.html#maybes"><i class="fa fa-check"></i><b>5.6</b> Maybes</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lin-a.html"><a href="lin-a.html"><i class="fa fa-check"></i><b>6</b> Linear Regression - Applied</a>
<ul>
<li class="chapter" data-level="6.1" data-path="lin-a.html"><a href="lin-a.html#example-research-question"><i class="fa fa-check"></i><b>6.1</b> Example research question</a></li>
<li class="chapter" data-level="6.2" data-path="lin-a.html"><a href="lin-a.html#application-with-wvs-data"><i class="fa fa-check"></i><b>6.2</b> Application with WVS data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="lin-a.html"><a href="lin-a.html#r-code"><i class="fa fa-check"></i><b>6.2.1</b> R Code</a></li>
<li class="chapter" data-level="6.2.2" data-path="lin-a.html"><a href="lin-a.html#interpretation-of-regression-table-in-practice"><i class="fa fa-check"></i><b>6.2.2</b> Interpretation of regression table in practice</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="lin-a.html"><a href="lin-a.html#regression-diagnostics-relatively-short"><i class="fa fa-check"></i><b>6.3</b> Regression Diagnostics (relatively short?)</a></li>
<li class="chapter" data-level="6.4" data-path="lin-a.html"><a href="lin-a.html#mediation"><i class="fa fa-check"></i><b>6.4</b> Mediation</a></li>
<li class="chapter" data-level="6.5" data-path="lin-a.html"><a href="lin-a.html#maybes-1"><i class="fa fa-check"></i><b>6.5</b> Maybes</a></li>
<li class="chapter" data-level="6.6" data-path="lin-a.html"><a href="lin-a.html#outlook"><i class="fa fa-check"></i><b>6.6</b> Outlook</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="lin-e.html"><a href="lin-e.html"><i class="fa fa-check"></i><b>7</b> Linear Regression - Exercises</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lin-e.html"><a href="lin-e.html#application-of-linear-regression"><i class="fa fa-check"></i><b>7.1</b> Application of Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="log-t.html"><a href="log-t.html"><i class="fa fa-check"></i><b>8</b> Logistic Regression - Theory</a>
<ul>
<li class="chapter" data-level="8.1" data-path="log-t.html"><a href="log-t.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="log-t.html"><a href="log-t.html#what-is-linear-regression-1"><i class="fa fa-check"></i><b>8.2</b> What is Linear Regression</a></li>
<li class="chapter" data-level="8.3" data-path="log-t.html"><a href="log-t.html#when-and-for-what-can-it-be-used"><i class="fa fa-check"></i><b>8.3</b> When and for what can it be used?</a></li>
<li class="chapter" data-level="8.4" data-path="log-t.html"><a href="log-t.html#formal"><i class="fa fa-check"></i><b>8.4</b> Formal</a></li>
<li class="chapter" data-level="8.5" data-path="log-t.html"><a href="log-t.html#regression-formula-1"><i class="fa fa-check"></i><b>8.5</b> Regression Formula</a></li>
<li class="chapter" data-level="8.6" data-path="log-t.html"><a href="log-t.html#interpretation-of-results"><i class="fa fa-check"></i><b>8.6</b> Interpretation of results</a></li>
<li class="chapter" data-level="8.7" data-path="log-t.html"><a href="log-t.html#maybes-2"><i class="fa fa-check"></i><b>8.7</b> Maybes</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="log-a.html"><a href="log-a.html"><i class="fa fa-check"></i><b>9</b> Logistic Regression - Applied</a>
<ul>
<li class="chapter" data-level="9.1" data-path="log-a.html"><a href="log-a.html#example-research-question-1"><i class="fa fa-check"></i><b>9.1</b> Example research question</a></li>
<li class="chapter" data-level="9.2" data-path="log-a.html"><a href="log-a.html#application-with-wvs-data-1"><i class="fa fa-check"></i><b>9.2</b> Application with WVS data</a></li>
<li class="chapter" data-level="9.3" data-path="log-a.html"><a href="log-a.html#r-code-1"><i class="fa fa-check"></i><b>9.3</b> R Code</a></li>
<li class="chapter" data-level="9.4" data-path="log-a.html"><a href="log-a.html#interpretation-of-regression-table-in-practice-1"><i class="fa fa-check"></i><b>9.4</b> Interpretation of regression table in practice</a></li>
<li class="chapter" data-level="9.5" data-path="log-a.html"><a href="log-a.html#regression-diagnostics-relatively-short-1"><i class="fa fa-check"></i><b>9.5</b> Regression Diagnostics (relatively short?)</a></li>
<li class="chapter" data-level="9.6" data-path="log-a.html"><a href="log-a.html#mediation-1"><i class="fa fa-check"></i><b>9.6</b> Mediation</a></li>
<li class="chapter" data-level="9.7" data-path="log-a.html"><a href="log-a.html#maybes-3"><i class="fa fa-check"></i><b>9.7</b> Maybes</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="log-e.html"><a href="log-e.html"><i class="fa fa-check"></i><b>10</b> Logistic Regression - Exercises</a>
<ul>
<li class="chapter" data-level="10.1" data-path="log-e.html"><a href="log-e.html#application-of-logistic-regression"><i class="fa fa-check"></i><b>10.1</b> Application of Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pm-t.html"><a href="pm-t.html"><i class="fa fa-check"></i><b>11</b> Prediction or Margins - Theory</a>
<ul>
<li class="chapter" data-level="11.1" data-path="pm-t.html"><a href="pm-t.html#predicted-probabilities"><i class="fa fa-check"></i><b>11.1</b> Predicted probabilities</a></li>
<li class="chapter" data-level="11.2" data-path="pm-t.html"><a href="pm-t.html#marginal-effects"><i class="fa fa-check"></i><b>11.2</b> Marginal Effects</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pm-e.html"><a href="pm-e.html"><i class="fa fa-check"></i><b>12</b> Prediction or Margins - Exercises</a>
<ul>
<li class="chapter" data-level="12.1" data-path="pm-e.html"><a href="pm-e.html#application-of-regression"><i class="fa fa-check"></i><b>12.1</b> Application of Regression</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="report-v.html"><a href="report-v.html"><i class="fa fa-check"></i><b>13</b> Reporting and Visualization</a>
<ul>
<li class="chapter" data-level="13.1" data-path="report-v.html"><a href="report-v.html#formatted-regression-tables"><i class="fa fa-check"></i><b>13.1</b> Formatted regression tables</a></li>
<li class="chapter" data-level="13.2" data-path="report-v.html"><a href="report-v.html#publication-ready-formatting-labelling-of-visuals"><i class="fa fa-check"></i><b>13.2</b> Publication-ready formatting/ labelling of visuals</a></li>
<li class="chapter" data-level="13.3" data-path="report-v.html"><a href="report-v.html#coefficient-plots"><i class="fa fa-check"></i><b>13.3</b> coefficient plots</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="dis-paper.html"><a href="dis-paper.html"><i class="fa fa-check"></i><b>14</b> Discussion of ideas and term papers</a></li>
<li class="chapter" data-level="15" data-path="out-look.html"><a href="out-look.html"><i class="fa fa-check"></i><b>15</b> Outlook</a>
<ul>
<li class="chapter" data-level="15.1" data-path="out-look.html"><a href="out-look.html#machine-learning"><i class="fa fa-check"></i><b>15.1</b> Machine Learning</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis with R for Social Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lin-t" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number"> 5</span> Linear Regression - Theory<a href="lin-t.html#lin-t" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="what-is-linear-regression" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> What is Linear Regression<a href="lin-t.html#what-is-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we use statistical modelling in social sciences there are two main
approaches.
The more classical approach is to use modelling for estimating the effect that
one or several independent variables have on one dependent variable. Maybe we
are interested in knowing if a higher income has an effect on life satisfaction
and if yes, what the direction and magnitude of this effect is. Does more money
actually make you happier?</p>
<p>The other and more recent approach is to use modelling for making predictions
with high accuracy. Based on the relationships between many independent
variables and one dependent variable, we try to predict the latter for actual
or hypothetical cases and their individual values for the independent variables.
This approach lies at the heart of <em>machine learning</em> and drives many of the
technologies we use on a daily basis from E-Mail spam filters to ChatGPT.</p>
<p>Linear regression is one of the many available modelling techniques and it can
serve both approaches lined out above. In this session we will focus on using
linear regression for estimating an effect of interest but we will return to
prediction at a later point in this course.</p>
<p>But how do we know if we should choose linear regression for a specific task?
This is not easy to answer as there are many alternatives and even variations of
linear regression which may be better suited for a specific empirical problem.
As this is an introduction to modelling and time is of the essence we opted to
reduce the options and focus on two kind of models over the next weeks. Linear
regression and logistic regression. Both are comparably easy to understand and
use. Also, if we understand both of these techniques, we are in a good position
to build upon our knowledge and learn all of those more complex and specific
models that we will encounter in textbooks and scientific papers.</p>
<p>With the pool of options trimmed down to two, the question remains unanswered.
Should I use linear or logistic regression for my task? But now the answer is
relatively straightforward. What is the type of our dependent variable? Is it
metric? Then we use linear regression. Is it binary or categorical? Then we use
logistic regression. Linear regression will be the focus of this and the next
weeks and then we will turn to logistic regression.</p>
<p>Now let us dive in and learn what linear regression is all about.</p>
</div>
<div id="examplary-research-question-data" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Examplary research question &amp; data<a href="lin-t.html#examplary-research-question-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let us imagine that we are interested in a research question that asks what
makes a good grade in a seminar paper. In particular we are interested in the
effect that the hours a student invests in working on it has on the grade. Based
on some theoretical considerations, and maybe some idealistic views, we derive
our main hypotheses that putting in more hours will result in a better grade.</p>
<p>Now we also - hypothetically - held a small survey and asked 200 imaginary
students some questions on how they approached writing a seminar paper. In
particular we asked them how much time they spent working on the paper, if they
have attended (almost) all seminar sessions, how closely they worked with their
lecturers in preparing the paper and what the mean grade for previous papers
was. As these imaginary students have already turned in their papers, we also
know the grades they achieved.</p>
<p>Please note, that this is data on <strong>imaginary</strong> students, meaning we have
simulated the data making some assumptions on how to achieve a good (or bad)
grade in a paper. The assumptions we made do not necessarily reflect the way
<em>you</em> write a good paper while still being based in our experience on what it
takes to achieve a good grade. But remember, no real students were harmed in
making up this example data.</p>
<p>Let us have a first look on the data:
XXX ALIGN WITH EDA XXX</p>
<pre><code>## Warning: package &#39;skimr&#39; was built under R version 4.2.3</code></pre>
<table>
<caption>(#tab:grades_skim)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">grades</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">200</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">7</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">factor</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">logical</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table style="width:100%;">
<colgroup>
<col width="17%" />
<col width="12%" />
<col width="17%" />
<col width="9%" />
<col width="11%" />
<col width="32%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">contact</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">3</td>
<td align="left">No : 80, In : 70, E-M: 50</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="left">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">attendance</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.76</td>
<td align="left">TRU: 153, FAL: 47</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<colgroup>
<col width="25%" />
<col width="10%" />
<col width="14%" />
<col width="6%" />
<col width="5%" />
<col width="7%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">grade</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2.97</td>
<td align="right">1.08</td>
<td align="right">1.00</td>
<td align="right">2.10</td>
<td align="right">3.00</td>
<td align="right">3.73</td>
<td align="right">5.00</td>
<td align="left">▅▆▇▆▅</td>
</tr>
<tr class="even">
<td align="left">hours</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">40.33</td>
<td align="right">6.29</td>
<td align="right">23.00</td>
<td align="right">36.00</td>
<td align="right">41.00</td>
<td align="right">45.00</td>
<td align="right">57.00</td>
<td align="left">▁▅▇▅▁</td>
</tr>
<tr class="odd">
<td align="left">previous_grades</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2.94</td>
<td align="right">0.96</td>
<td align="right">1.00</td>
<td align="right">2.30</td>
<td align="right">2.95</td>
<td align="right">3.62</td>
<td align="right">5.00</td>
<td align="left">▅▇▇▆▂</td>
</tr>
<tr class="even">
<td align="left">previous_grades_centered</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.00</td>
<td align="right">0.96</td>
<td align="right">-1.94</td>
<td align="right">-0.64</td>
<td align="right">0.01</td>
<td align="right">0.69</td>
<td align="right">2.06</td>
<td align="left">▅▇▇▆▂</td>
</tr>
<tr class="odd">
<td align="left">hours_centered</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.00</td>
<td align="right">6.29</td>
<td align="right">-17.33</td>
<td align="right">-4.33</td>
<td align="right">0.67</td>
<td align="right">4.67</td>
<td align="right">16.67</td>
<td align="left">▁▅▇▅▁</td>
</tr>
</tbody>
</table>
<p>Right now, the observations are ordered by the grade of the seminar paper which
run from <span class="math inline">\(1.0\)</span> to <span class="math inline">\(5.0\)</span> in increments of <span class="math inline">\(0.1\)</span>. While this is somewhat
unrealistic - the german grading system actually only uses theincrements <span class="math inline">\(.0\)</span>,
<span class="math inline">\(.3\)</span> and <span class="math inline">\(.7\)</span> - simulating the data in this way will make the demonstrations on
linear regression easier and more straightforward. The variable
<code>previous_grades</code> is set up in the same way and represents the mean of the
grades the student received up to this point <code>hours</code> represents the time a
student spent on writing the paper, ranging from <span class="math inline">\(23 - 57\)</span> hours, with a mean of
about <span class="math inline">\(40\)</span>. Besides these metric variables, the data set also contains two
categorical measures. <code>attendance</code> is a <em>dummy variable</em>, meaning it can only
have the values <span class="math inline">\(1\)</span> or <span class="math inline">\(0\)</span> or <code>TRUE</code> and <code>FALSE</code> in this case, as it is saved as
a logical variable. <code>TRUE</code> represents that a student attended almost all seminar
sessions before writing the paper - which about <span class="math inline">\(77%\)</span> did -, <code>FALSE</code> states that
they did not.
<code>contact</code> is a factor variable with three categories and shows the answers to
the imaginary question on how much contact the student had to the lecturer
before starting the writing process. Besides <code>No contact</code> the students could
have had <code>E-Mail</code> contact to state ther research question and get some short
written feedback or meet the lecturer <code>In Person</code> to achieve a deeper discussion
of the question and laid out plan for writing the paper.
The two additional variables are versions of <code>previous_grades</code> and <code>hours</code> that
are centered on their respective means. They will come into play at a later
point in this session.</p>
<p>Let’s have a look at some observations.</p>
<pre><code>## # A tibble: 10 × 7
##    grade hours previous_grades attendance contact   previous_grades_centered
##    &lt;dbl&gt; &lt;int&gt;           &lt;dbl&gt; &lt;lgl&gt;      &lt;fct&gt;                        &lt;dbl&gt;
##  1     1    50             1.4 TRUE       E-Mail                      -1.54 
##  2     1    46             1   TRUE       E-Mail                      -1.94 
##  3     1    42             1   TRUE       In Person                   -1.94 
##  4     1    49             1   FALSE      In Person                   -1.94 
##  5     1    42             1.2 TRUE       In Person                   -1.74 
##  6     1    46             1.8 TRUE       In Person                   -1.14 
##  7     1    44             1.4 FALSE      In Person                   -1.54 
##  8     1    45             2   TRUE       In Person                   -0.935
##  9     1    48             1   TRUE       In Person                   -1.94 
## 10     1    45             2   TRUE       In Person                   -0.935
## # ℹ 1 more variable: hours_centered &lt;dbl&gt;</code></pre>
<p>From this first 10 rows, we can see that the students with the best grades spent
more than 40 hours on writing, have already achieved good grades in their papers
up to this point and at least had some contact to the lecturers. Most also
regularly attended the seminar but two did not and still achieved a <span class="math inline">\(1.0\)</span> in
their grade.</p>
<p>So what makes a bad grade?</p>
<pre><code>## # A tibble: 10 × 7
##    grade hours previous_grades attendance contact    previous_grades_centered
##    &lt;dbl&gt; &lt;int&gt;           &lt;dbl&gt; &lt;lgl&gt;      &lt;fct&gt;                         &lt;dbl&gt;
##  1   4.8    37             4.2 TRUE       No contact                    1.27 
##  2   4.8    38             4.3 TRUE       E-Mail                        1.36 
##  3   4.8    35             4.4 TRUE       E-Mail                        1.47 
##  4   4.9    40             4.2 TRUE       E-Mail                        1.27 
##  5   5      35             3.9 FALSE      No contact                    0.965
##  6   5      41             4.9 TRUE       No contact                    1.97 
##  7   5      24             4.7 TRUE       E-Mail                        1.76 
##  8   5      33             5   TRUE       E-Mail                        2.06 
##  9   5      29             4.1 FALSE      E-Mail                        1.16 
## 10   5      50             4.6 FALSE      E-Mail                        1.66 
## # ℹ 1 more variable: hours_centered &lt;dbl&gt;</code></pre>
<p>Here the picture seems less clear. While most students did not put in as many
hours, some did and still failed to pass. Half of the students that received a
<span class="math inline">\(5.0\)</span> regularly attended and most at least had E-Mail contact before writing
their paper. What seems to be more consistent though is that the mean of the
previous grades is rather low.</p>
<p>So what do we know now? Does a good or bad track record in grades predict all
future grades? This seems not only unrealistic but also a kind of sad take home
message. To get a better understanding on which of the potential influential
variables had an effect on the final grade and what the magnitude and direction
of these effects was, we now turn to linear regression.</p>
</div>
<div id="simple-linear-regression" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Simple Linear Regression<a href="lin-t.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In a <em>simple linear regression</em>, the model is used to describe the relationship
between <em>one</em> dependent and <em>one</em> independant or explanatory variable. The
question this model can answer for us is, by how much does the dependent
variable increase or decrease, when the explanatory variable increases by <span class="math inline">\(1\)</span>?</p>
<p>Returning to our exemplary research question on what makes a good grade in a
seminar paper an intuitive hypotheses would be, that the grade gets better the
more hours a student invests in writing the paper. In this case we assume a
linear relationship between the independent variable <code>hours</code> and the dependent
variable <code>grade</code>. As german grades are better the lower their value, we thus
would assume a negative effect from <code>hours</code> on <code>grade</code>.</p>
<p>Before turning to the formalities and practical application of a simple linear
regression model, let us first have a look on this relationship by plotting the
variables against each other.</p>
<p><img src="_main_files/figure-html/plot_grade_hours-1.png" width="672" /></p>
<p>When we are talking about dependent and independent variables, there is the
convention to plot former on the x-axis and the latter on the y-axis. So the
<em>y-variable</em> is to be explained and the <em>x-variable</em> is used to explain it.
This convention will also be used in all formulas in this seminar.</p>
<p>Looking at the plot we first see a cloud of dots, representing all combinations
of <code>hours</code> and <code>grade</code> in all our <span class="math inline">\(200\)</span> observations. It may be hard to pick out
any pattern, but looking closely we can observe that overall the dots seem to
follow a downward slope from the upper left - indicating few hours worked and a
worse grade - towards the lower right - indicating more invested hours and a
better grade. This would be the relationship stated in our hypotheses. The more
hours a student works on a seminar paper the better the final grade will be.</p>
<p>We can try to describe this pattern by adding a line from the upper left to the
lower right.</p>
<p><img src="_main_files/figure-html/plot_grade_hours_wild_guess-1.png" width="672" /></p>
<p>This describes the realtionship between the two variables as linear. Each hour
invested decreases the grade by a certain amount, for this proposed line by
exactly <span class="math inline">\(0.08\)</span> points. Remember that decreasing the value of the grade actually
means getting a better grade.</p>
<p>But is this the only possible line or even the <em>correct</em> one? Most certainly not
as the values used to draw the line were only a wild guess by the authors. We
could imagine several other lines that also look more or less reasonable - as
well as some that look unreasonable - and add them to the plot.</p>
<p><img src="_main_files/figure-html/plot_grade_hours_wild_guesses-1.png" width="672" /></p>
<p>While we have some intution, that especially the green line misses the mark by a
lot, we can’t really decide between the others just by looking at the plot. The
data points are way to dispersed to see the relationship clearly.</p>
<p>The goal of using a simple linear regression model is to identify the <em>one</em> line
that describes the relationship the best. The <em>best</em> meaning, with as little
error as possible.</p>
<p>XXX OVERLAPPING DOTS? XXX</p>
<div id="regression-formula" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Regression Formula<a href="lin-t.html#regression-formula" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To understand how these lines in the above plot were conceived and how to find
the line with the best <em>fit</em>, i.e. the lowest error, we have to understand the
formular for linear regression. While formulas may always be kind of daunting,
we are in luck as tis particular one is actually quite easy to understand,
especially when paired with a graphical representation.</p>
<p><span class="math display">\[y = \beta_0 + \beta_1*x_1 + \epsilon\]</span></p>
<p>Let us first look at the parts we already know. <span class="math inline">\(y\)</span> is the dependent variable,
in our case the grade achieved. So one thing is for sure, the whole right part
of the equation has to be used to calculate the value of <span class="math inline">\(y\)</span> from the data, i.e.
the dependent variable <span class="math inline">\(x\)</span>. Here we have three terms. Let us skip the first one
for now and focus on the second one <span class="math inline">\(\beta_1*x_1\)</span>.</p>
<p><span class="math inline">\(x_1\)</span> is the dependent variable, in our case <code>hours</code>. <span class="math inline">\(\beta_1\)</span> is the
<em>redression coefficient</em> for <span class="math inline">\(x_1\)</span>. This value gives us the <em>slope</em> of the
regression line. Based on this, we can start rewriting the general formula and
tailor it to our specific use case.</p>
<p><span class="math display">\[y_{grade} = \beta_0 + \beta_{hours}*x_{hours} + \epsilon\]</span></p>
<p>Let us return to the first wild guess we made above.</p>
<p><img src="_main_files/figure-html/plot_grade_hours_wild_guess_expl_slope-1.png" width="672" /></p>
<p>Here we guessed, that an increase in time invested of one hour decreases the
value of <code>grade</code> by <span class="math inline">\(0.08\)</span>. This is the slope of the red line and thus also the
coefficient in the regression formula that is used in computing said line. So,
<span class="math inline">\(\beta_{hours} = -0.08\)</span>. We can insert this value into our formula.</p>
<p><span class="math display">\[y_{grade} = \beta_0 -0.08*x_{hours} + \epsilon\]</span></p>
<p>In this way the value of <span class="math inline">\(x_{hours}\)</span> is multiplied by <span class="math inline">\(-0.08\)</span>. Let us assume a
student worked <span class="math inline">\(40\)</span> hours on their paper. <span class="math inline">\(-0.08*40\)</span> being <span class="math inline">\(-3.2\)</span>, we know, that
working 40 hours on a paper <em>on average</em> - more on that later - leads to a <span class="math inline">\(3.2\)</span>
lower grade value and thus a better grade. But <span class="math inline">\(3.2\)</span> lower than what?</p>
<p>Looking at the formula again, we see that subtract this value from <span class="math inline">\(\beta_0\)</span>.
This is the <em>intercept</em>, the value at which the line intersects with the y-axis.
Let us zoom out on our plot, to see what happens.</p>
<p><img src="_main_files/figure-html/plot_grade_hours_wild_guess_expl_intercept-1.png" width="672" /></p>
<p>We can now see the point where the red line intersects with the y-axis. This is
the intercept of this line, i.e. <span class="math inline">\(\beta_0 = 6\)</span>.</p>
<p><span class="math display">\[y_{grade} = 6 -0.08*x_{hours} + \epsilon\]</span></p>
<p>If we now again assume a time investment of <span class="math inline">\(40\)</span> hours, we can compute
<span class="math inline">\(6-0.08*40 = 2.8\)</span>. So our red regression line - which is still only a wild guess
- assumes, that working 40 hours on a seminar paper will result in a grade of
<span class="math inline">\(2.8\)</span>, on avarage. We can mark these values in our plot</p>
<p><img src="_main_files/figure-html/plot_grade_hours_wild_guess_expl_40hours-1.png" width="672" /></p>
<p>The red dot is the intersection of the values <code>hours = 40</code> and <code>grade = 2.8</code>.
As this is the value for <span class="math inline">\(y\)</span> our regression line assumes a student with a time
investment of 40 hours achieves, the red dot also lies exactly on the red line.</p>
<p>But if we look at the plot once again, we can see that most actual observations
for students that invested 40 hours do not actually lie on the regression line
but are scattered above and below the line. So some of these students achieve
much worse or much better grades than <span class="math inline">\(2.8\)</span> investing the same amount of time in
their work. This leads us to the last part of the formula, <span class="math inline">\(\epsilon\)</span>.</p>
<p>This is the <em>error term</em>. Having data that is dispersed like this - and any real
world data will always be - our linear line will never be able to pass exactly
through every data point. Some points may lie exactly on the line, but many or
most will not.</p>
<p>We can visualize this. To keep the plot readable, we only do this for some
random observations but in reality the distance of every data point from the
regression line is taken into account.</p>
<pre><code>## # A tibble: 5 × 7
##   grade hours previous_grades attendance contact    previous_grades_centered
##   &lt;dbl&gt; &lt;int&gt;           &lt;dbl&gt; &lt;lgl&gt;      &lt;fct&gt;                         &lt;dbl&gt;
## 1   2.3    45             2.6 TRUE       No contact                   -0.335
## 2   1.9    44             2.8 TRUE       In Person                    -0.135
## 3   3.1    38             3.7 TRUE       In Person                     0.765
## 4   3.3    40             3.4 TRUE       E-Mail                        0.465
## 5   4.6    54             4.5 TRUE       No contact                    1.56 
## # ℹ 1 more variable: hours_centered &lt;dbl&gt;</code></pre>
<p><img src="_main_files/figure-html/plot_grade_hours_wild_guess_expl_residuals-1.png" width="672" /></p>
<p>The distance of these or rather all points from the line, the <em>residuals</em>, are
represented in the error term <span class="math inline">\(\epsilon\)</span>. It is a measure for how wrong our line
is in describing the data in it’s entirety. So why is it wrong? We can not say
for sure, but there are two common main reasons.</p>
<p>For one, there may be other variables that also influence the relationship
between invested hours and achieved grade, something that we will return to
later in this session when we expand the idea of linear regression to multiple
independent variables.</p>
<p>But there is also random variation present in every bit of real world data.
While our data is simulated we also added random variation on purpose. Because
this is what real world data is, it’s messy and it’s noisy.</p>
<p>Not every seminar paper that had the same time investment, e.g. 40 hours, will
have the same quality in results. There may be other influential variables, e.g.
the student’s general skill level or if they sought assistance by their lecturer
in preparing the paper, influencing the final grade. But even if the quality of
the paper after working 40 hours would be the same for each student, measurement
error, i.e. noise, will be introduced because not every lecturer will grade
exactly the same or maybe because papers were submitted at different time
points and grading standards may have changed. If we can not measure these
variables we have to accept these unobservable sources of noise and hope, where
<em>hope</em> actually means thorough theoretical and methodical thinking, that we can
still measure our effect of interest. But his also means, that measuring and
modelling <strong>always</strong> includes uncertainty. We never know for certain if and to
what extent our results are influenced by unobservable variables and random
variation. Still, there are ways to assess this uncertainty, which we will
regularly return to during the course. This should not stop quantitative
social scientists from making strong or even bold arguments based in thorough
theoretical thinking and responsible data analysis, but we always have to
acknowledge the uncertainty included in every step and make it a part of our
interpretations and conclusions.</p>
<p>XXX MAYBE SHORTEN THE SERMON… XXX</p>
<p>The error term <span class="math inline">\(\epsilon\)</span> is the final piece of the puzzle in actually computing
a linear regression model. Without jumping into the mathematics of it all, the
technique that is used to estimate the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> is
called <em>OLS</em> - Ordinary Least Squares. What it basically does, is to take the
squares of all residuals, i.e. the distances of the data points from the
regression line, sum them up and minimise this value. All this substantialy
means is, that OLS searches the regression line with lowest amount of error,
i.e. the lowest overall distance from the actual data points.</p>
<p>This computation gives us estimates for the regression coefficients in this
formula:</p>
<p><span class="math inline">\(\hat{y} = b_0 +b_1*x_1\)</span></p>
<p>We can see two differences to the formula we started with. First, we write
<span class="math inline">\(\hat{y}\)</span> - pronounced as “y hat” - instead of <span class="math inline">\(y\)</span>. At the same time, we exclude
the error term <span class="math inline">\(\epsilon\)</span>. This means that we are no longer computing the actual
value of <span class="math inline">\(y\)</span>, as in the point on the regression line for a certain value of
<span class="math inline">\(x_1\)</span> <span class="math inline">\(+\)</span> the error, but the estimate <span class="math inline">\(\hat{y}\)</span>, as in the point on the
regression line that is predicted for a certain value of <span class="math inline">\(x_1\)</span>. Second, we write
<span class="math inline">\(b\)</span> instead of <span class="math inline">\(\beta\)</span>. This also alludes to the fact that we are now
computing an estimate for the coefficients based on the data available and not
the real and unknown value of <span class="math inline">\(\beta\)</span>.</p>
<p>XXX MAYBE ALSO SOME CUTTING REQUIRED XXX</p>
<p>XXX include “on average” XXX</p>
</div>
<div id="regressing-grade-on-hours" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Regressing <code>grade</code> on <code>hours</code><a href="lin-t.html#regressing-grade-on-hours" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have a firmer understanding on what linear regression actually is
and does, we can finally get to the fun part and use the technique for
estimating the effect of <code>hours</code> on <code>grade</code> or in other words, regress
<code>grade</code> on <code>hours</code>.</p>
<pre><code>## 
## Call:
## lm(formula = grade ~ hours, data = grades)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.88006 -0.83961 -0.08006  0.77006  2.53881 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  5.07912    0.47306  10.737  &lt; 2e-16 ***
## hours       -0.05236    0.01159  -4.517 1.07e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.028 on 198 degrees of freedom
## Multiple R-squared:  0.09344,    Adjusted R-squared:  0.08886 
## F-statistic: 20.41 on 1 and 198 DF,  p-value: 1.075e-05</code></pre>
<p>This is the output from a simple linear regression for <code>grade</code> on <code>hours</code> from
R. How to do this in practice and what the first to lines mean will be the topic
of the next sesion. For now we will focus on the coefficient block and
introduce the additional elements of the output on by one during this session.</p>
<p>The column <code>Estimate</code> gives us the values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> discussed
above. The estimated coefficient for <code>hours</code> tells us that out intuition was
right, the more hours a student invests in writing a paper, the better the grade
will be. In this case every additional hour spent on working will decrease the
value of the grade by <span class="math inline">\(-0.05236\)</span> points. In keeping with the example of a 40
hour workload this leads to a decrease of <span class="math inline">\(-0.05236 * 40 = -2.0944\)</span> points.
Adding the intercept from the same column, the estimated grade after working 40
hours is <span class="math inline">\(5.07912 -0.05236 * 40 = 2.98472\)</span>. So on average a student from our
simulated data set will pass after 40 hours of work but will not get a great
grade.
Remember, this is the expected average value. This does not mean that some
students will not get better or worse grades, or even fail to pass, after this
amount of time investment, as we hav seen in the plot.</p>
<p>Now that we know the coefficients for the regression line with the best fit,
i.e. the lowest error, we can again visualise the result.</p>
<p><img src="_main_files/figure-html/plot_lm_grade_hours-1.png" width="672" /></p>
<p>Now, what grade can a student expect, on average, if they invest exactly 0
hours, i.e. do nothing and hand in a blank paper. We can look at the graph or to
achieve a more precise result, calculate it.</p>
<p><span class="math display">\[5.07912 -0.05236 * 0 = 5.07912\]</span></p>
<p>As <span class="math inline">\(x_{hours} = 0\)</span> for this theoretical example, the estimated value <span class="math inline">\(\hat{y}\)</span>
or <span class="math inline">\(y_{grade}\)</span> is the same as the intercept <span class="math inline">\(\beta_0\)</span>. This is what the
intercept represents in general, the estimated value <span class="math inline">\(\hat{y}\)</span> when the
dependent variable is <span class="math inline">\(0\)</span>.</p>
<p>Now, investing zero hours in a seminar paper is not only not advisable, it is
also not a value we observed in our data. If the data would include observations
with zero hours of time invested, the grade would be a firm <span class="math inline">\(5.0\)</span> and the same
would be true for low single digits, i.e. turning in a two-pager as a seminar
paper. The takeaway is, that the model is highly dependent on the data that it
is trained on. If the data would have included such cases we could expect a
higher intercept and a steeper slope, i.e. stronger negative coefficient.</p>
<p>Luckily all our simulated students have put in at least some hours. But as we do
not have data for zero to <span class="math inline">\(22\)</span> hours, we can not really make reliable estimates
in this range. Because of this, it does not really make sense to enter <code>hours</code>
into the regression model as ranging from <span class="math inline">\(0\)</span> to <span class="math inline">\(57\)</span>. One solution that is
often used for metric variables is to center them on their mean. This can be
achieved by simply subtracting the mean of <span class="math inline">\(x\)</span> from each individual value:
<span class="math inline">\(x_i - \bar{x}\)</span>.</p>
<p>We can now rerun the regression.</p>
<pre><code>## 
## Call:
## lm(formula = grade ~ hours_centered, data = grades)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.88006 -0.83961 -0.08006  0.77006  2.53881 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     2.96750    0.07267  40.835  &lt; 2e-16 ***
## hours_centered -0.05236    0.01159  -4.517 1.07e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.028 on 198 degrees of freedom
## Multiple R-squared:  0.09344,    Adjusted R-squared:  0.08886 
## F-statistic: 20.41 on 1 and 198 DF,  p-value: 1.075e-05</code></pre>
<p>Comparing the results to the first model shows us, that the coefficient for
<span class="math inline">\(b_{hours\_centered}\)</span> is exactly the same as for <span class="math inline">\(b_{hours}\)</span>. So the effect
of working more hours has not changed. What has changed is the value of the
intercept. This will make more sense if we again plot the regression line.</p>
<p><img src="_main_files/figure-html/plot_lm_grade_hours_centered-1.png" width="672" /></p>
<p>By centering the x-Variable on its mean we have changed its interpretation.
A value of <code>hours = 0</code> now stands for investing as much time as is the mean
of <code>hours</code> in the whole data set, which in this case is <span class="math inline">\(40.33\)</span> hours. Positive
values indicate that a student worked <span class="math inline">\(x\)</span> hours more, negatives indicate <span class="math inline">\(-x\)</span>
hours less compared to the mean. In this way, we also moved the y-axis and thus
changed the interpretation of the intercept. Its new value of <span class="math inline">\(2.9675\)</span> now
indicates the estimate for a student who invests the mean value of <code>hours</code> in
their work, i.e. <span class="math inline">\(40.33\)</span>. We will use this version of the variable for the rest
of the session.</p>
</div>
</div>
<div id="multiple-linear-regression" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Multiple Linear Regression<a href="lin-t.html#multiple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Maybe explaining the grade a student receives solely based on the hours of
invested time, does not paint the whole picture. As we have alluded to, there
may be other variables that could also have an effect of the final grade.</p>
<p>A <em>simple linear regression</em> only allows for one independent variable. This is
why we need <em>multiple linear regression</em> if we want to start introducing
additional variables into the model. Luckily this is easy to understand as we
already know the formula for a simple linear regression.</p>
<p><span class="math display">\[y = \beta_0 + \beta_1*x_1 + \epsilon\]</span></p>
<p>To change a simple into a multiple linear regression, we just start adding the
additional variables and their coefficients additively to the formula.</p>
<p><span class="math display">\[y = \beta_0 + \beta_1*x_1 + \beta_2*x_2 + ... + \beta_k*x_k + \epsilon\]</span></p>
<p>So to add a second variable and its coeffcient we add the term <span class="math inline">\(+ \beta_2*x_2\)</span>
and so on until we added all independent varibles of interest <span class="math inline">\(k\)</span> to the model.
Everything else works exactly as described above for the simple model.</p>
<div id="adding-additional-variables" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Adding additional variables<a href="lin-t.html#adding-additional-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We already expected that the mean of the previous grades could be a strong
predictor for future grades. We could understand these as a <em>proxy</em> variable for
the general skill level of a student. The higher the skill level, the higher
previous grades will have been.</p>
<p>How we can add additional variables in R code will again be a topic for the next
session, but let us look at the results of a regression of <code>grade</code> on
<code>hours_centered</code> and <code>previous_grades_centered</code>, the latter being centered on the
mean previous grade of <span class="math inline">\(2.935\)</span>.</p>
<pre><code>## 
## Call:
## lm(formula = grade ~ hours_centered + previous_grades_centered, 
##     data = grades)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.44462 -0.30556  0.00622  0.32878  1.31002 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               2.967500   0.038316  77.449   &lt;2e-16 ***
## hours_centered           -0.056543   0.006114  -9.248   &lt;2e-16 ***
## previous_grades_centered  0.904079   0.039830  22.699   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5419 on 197 degrees of freedom
## Multiple R-squared:  0.7492, Adjusted R-squared:  0.7467 
## F-statistic: 294.3 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As we added a new variable, we now see three coefficients.
The intercept has not changed. It now indicates the estimated grade for a
student who invests the mean amount of hours, <span class="math inline">\(40.33\)</span>, and whose previous grades
are exactly <span class="math inline">\(2.935\)</span>.</p>
<p>The coefficient for <code>hours_centered</code> got mildly more negative, still telling us
that the value of <code>grade</code> gets lower, the more hours are invested in writing the
paper. This coefficient now gives us the effect while <em>controlling</em> for the
effect of <code>previous_grades_centered</code>. This is what multiple linear regression
does, giving us the coefficients for our variables of interest while keeping all
other independent variables at specific values. As we have centered the variable
for previous grades, the coefficient for <code>hours centered</code> gives us the effect
when the previous grades were exactly at the mean of <span class="math inline">\(2,935\)</span>.</p>
<p>In the same way, the coefficient for <code>previous_grades_centered</code> gives us the
effect of previous grades when the invested hours are controlled for, in this
case when the invested hours were exactly <span class="math inline">\(40.33\)</span>. The coefficient is rather
high and positive. This indicates that a student with a previous grade value
that is <span class="math inline">\(1\)</span> above the mean, is estimated to receive a new grade that is <span class="math inline">\(0.9\)</span>
points above the intercept. This means, that the previous grade is a very strong
predictor for the new grade.</p>
<p>While plotting in more than two dimensions gets really hard, we can still
calculate <span class="math inline">\(\hat{y}\)</span> for certain values of both independent variables.
We already know the predicted grade for a student with mean values on both
independent variables, as this is the intercept. To make sure that we correct,
we can calculate it again.</p>
<p><span class="math display">\[b_0 + b_{hours\_centered}*0 + b_{previous\_grades\_centered}*0 = 2.9675\]</span></p>
<p>For this case we can see, that the previous grade actually is a strong
predictor, as the previous and new grades are substantially the same.</p>
<p>What if a student whose previous grades were <span class="math inline">\(1\)</span> above the mean, so just below
<span class="math inline">\(4.0\)</span> but who decides to invest <span class="math inline">\(10\)</span> hours more than the mean for the new paper?</p>
<p><span class="math display">\[2.9675 - 0.056543 * 10 + 0.904079 * 1 = 3.306149\]</span></p>
<p>So the good message is, while previous grades are a strong predictor, putting in
more hours still leads to better grades.</p>
<p>What if a really good student decides to rely on their skill and to work less
this time?</p>
<p><span class="math display">\[2.9675 - 0.056543 * -10 + 0.904079 * -2 = 1.724772\]</span></p>
<p>While <span class="math inline">\(1.7\)</span> is still a very good grade, working 10 less hours than the mean of
students leads to a substantially worse estimate compared to the about <span class="math inline">\(1.0\)</span>
received in previous grades.</p>
</div>
<div id="adding-dummy-variables" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Adding dummy variables<a href="lin-t.html#adding-dummy-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Another variable that could be of interest in explaining the received grade,
is if a student attended most of the seminar sessions.
<code>attendance</code> holds this information in the form of a dummy variable. Dummies can
only have two states. “Yes” or “No”, “1” or “0” or in this case “<code>TRUE</code>” or
“<code>FALSE</code>”.</p>
<p>Let us add the variable to our model.</p>
<pre><code>## 
## Call:
## lm(formula = grade ~ hours_centered + previous_grades_centered + 
##     attendance, data = grades)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.41059 -0.30910  0.01667  0.35607  1.29849 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               3.157411   0.078658  40.141  &lt; 2e-16 ***
## hours_centered           -0.053942   0.006088  -8.860 4.85e-16 ***
## previous_grades_centered  0.911802   0.039282  23.212  &lt; 2e-16 ***
## attendanceTRUE           -0.248250   0.090246  -2.751   0.0065 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5331 on 196 degrees of freedom
## Multiple R-squared:  0.7586, Adjusted R-squared:  0.7549 
## F-statistic: 205.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This gives us a new line in the R Output holding an estimate for
<code>attendanceTRUE</code>. What is meant by this? In contrast to the metric variables we
have uses in our model up to this point, a dummy variable - or binary variable -
can only have two states. As we are using a logical variable here, it can only
have the value <code>TRUE</code> - here indicating regular attendance - or <code>FALSE</code>. So what
the output shows us, is the effect of attendance being <code>TRUE</code> compared to being
<code>FALSE</code>. If a student did regularly attend the seminar, the estimated grade is
<span class="math inline">\(-0.248250\)</span> lower compared to when they did not.</p>
<p>We can observe what happens in the formula:</p>
<p><span class="math display">\[\hat{y} = b_0 + b_{hours\_centered}*x_{hours\_centered} + b_{previous\_grades\_centeterd}*x_{previous\_grades\_centeterd} + b_{attendance} * x_{attendance}\]</span></p>
<p>If you calculate with <code>TRUE</code> and <code>FALSE</code> in R, the values <span class="math inline">\(1\)</span> and <span class="math inline">\(0\)</span> are used
respectively. So <span class="math inline">\(x_{attendance}\)</span> can either have the value <span class="math inline">\(1\)</span> for regular
attendance or <span class="math inline">\(0\)</span> for not so regular attendance.</p>
<p>If a student did regularly attend, the coefficient $b_{attendance} becomes a
part of the estimate <span class="math inline">\(\hat{y}\)</span>:</p>
<p><span class="math display">\[\hat{y} = b_0 + b_{hours\_centered}*x_{hours\_centered} + b_{previous\_grades\_centeterd}*x_{previous\_grades\_centeterd} + b_{attendance} * 1\]</span></p>
<p>If stduent did not regularly attended, this happens:</p>
<p><span class="math display">\[\hat{y} = b_0 + b_{hours\_centered}*x_{hours\_centered} + b_{previous\_grades\_centeterd}*x_{previous\_grades\_centeterd} + b_{attendance} * 0\]</span>
<span class="math display">\[\hat{y} = b_0 + b_{hours\_centered}*x_{hours\_centered} + b_{previous\_grades\_centeterd}*x_{previous\_grades\_centeterd}\]</span></p>
<p>The coeeffcient is no longer a part of the estimate. One can basically say, the
coefficient gets switched on or off by the value of the dummy variable.</p>
<p>So while the estimate for a student with mean values for invested hours and
previous grades who did not attend is the intercept of <span class="math inline">\(3.157411\)</span> for the same
student with attendance we can calculate the estimate as:</p>
<p><span class="math display">\[3.157411 - 0.053942*0 + 0.911802*0 - 0.248250 * 1 = 3.157411 - 0.248250 = 2.909161\]</span></p>
<p>It seems attending class is an easy way to raise one’s grades.</p>
</div>
<div id="adding-categorical-variables" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Adding categorical variables<a href="lin-t.html#adding-categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We have one further variable in our simulated data set that could be of interest
in explaining, what makes a good grade in a seminar paper.<code>contact</code> is a factor
variable. It can take three different categories. <code>No contact</code> indicates that
the student did not contact the lecturer to discuss a research question or the
laid out plan for the paper. <code>E-Mail</code> means that there was some written contact
and at least the basics for the paper were discussed before writing. Lastly,
<code>In Person</code> stands for an in depth discussion with the lecturer, clearing up
problems beforehand and having a more stringent vision for the paper before
writing the first word.</p>
<p>Let us add the variable to our model.</p>
<pre><code>## 
## Call:
## lm(formula = grade ~ hours_centered + previous_grades_centered + 
##     attendance + contact, data = grades)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.3835 -0.2525  0.0167  0.2678  0.9347 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               3.617949   0.068077  53.145  &lt; 2e-16 ***
## hours_centered           -0.050830   0.004433 -11.466  &lt; 2e-16 ***
## previous_grades_centered  0.874123   0.028657  30.503  &lt; 2e-16 ***
## attendanceTRUE           -0.324653   0.065781  -4.935 1.72e-06 ***
## contactE-Mail            -0.413808   0.069817  -5.927 1.39e-08 ***
## contactIn Person         -0.853252   0.063964 -13.340  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3869 on 194 degrees of freedom
## Multiple R-squared:  0.8741, Adjusted R-squared:  0.8709 
## F-statistic: 269.4 on 5 and 194 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Wait, we entered three categories into the model and got estimates for two of
them. What happened? What R does is to create two dummy variables on the fly.
The first discerns between having E-Mail contact or no contact at all. The
second one between having contact in person to no contact at all. So for
categorical variables in regression models we always compare being in one
category to being in the <em>base category</em>. In this case the base category is
<code>No contact</code> but we could also change the base category. It depends on what we
are interested in comparing to. For our example comparing the effects of having
more in depth contact to having none makes sense.</p>
<p>Let us look at our formula again:</p>
<p><span class="math display">\[\hat{y} = b_0 + b_{hours\_centered}*x_{hours\_centered} + b_{previous\_grades\_centeterd}*x_{previous\_grades\_centeterd} + b_{attendance} * x_{attendance} + b_{E-Mail} * x_{E-Mail} + b_{In Person} * x_{In Person}\]</span></p>
<p>Now there are three possibilities. A student can have no contact at all. In this
case both dummy variables equal <span class="math inline">\(0\)</span>. To make our formula easier to read, we have
abbreviated the middle part for now:</p>
<p><span class="math display">\[\hat{y} = b_0 + ... + b_{E-Mail} * 0 + b_{In Person} * 0\]</span>
So in this case, controlling all other independent variables at their default
values, the mean for the metric variables, <code>FALSE</code> for <code>attendance</code>, the
intercept gives us the estimate for the grade as both dummy variables that
were created for <code>contact</code>are “switched off”.</p>
<p>THe two other possibilities are that a student either had E-Mail contact or an
in person discussion:</p>
<p><span class="math display">\[\hat{y} = b_0 + ... + b_{E-Mail} * 1 + b_{In Person} * 0\]</span></p>
<p><span class="math display">\[\hat{y} = b_0 + ... + b_{E-Mail} * 0 + b_{In Person} * 1\]</span></p>
<p>In both cases the relevant dummy variable is “switched on” while the other does
not factor into the equation.</p>
<p>Looking at the estimates, we can see that having contact to the lecturer before
writing has strong negative effects, resulting in better grades. Having E-Mail
contact reduces the value of <code>grade</code> by <span class="math inline">\(-0.413808\)</span> points, having an in person
discussion by <span class="math inline">\(-0.853252\)</span>.</p>
<p>So what grade can a student whose previous grades were at the mean of <span class="math inline">\(2.935\)</span>,
but who decided to put in 20 hours more compared to their peers, regularly
attend the seminar and have an in-depth personal discussion before writing their
paper expect on average as their new grade?</p>
<p><span class="math display">\[3.617949 - 0.050830 * 20 + 0.874123 * 0 - 0.324653 * 1 - 0.413808 * 0 - 0.853252 * 1 = 1.423444\]</span></p>
<p>Putting in the hours, attending and working with your lecturer seems to pay off,
at least in our simulated data set.</p>
<!-- ### Adding interactions -->
<!-- CUT FOR NOW -->
<!-- ``` {r reg_grade_hours_prev_att_contact_interaction, echo = FALSE} -->
<!-- lm(grade ~ hours_centered + previous_grades_centered + attendance + contact + hours_centered * contact, grades) %>% summary() -->
<!-- ``` -->
</div>
</div>
<div id="returning-to-our-research-question" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Returning to our research question<a href="lin-t.html#returning-to-our-research-question" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Our examplary research question concerned itself with what makes a good grade in
a seminar paper. In particular we were interested in the effect of the invested
hours, as our main hypothesis was that more hours lead to better grades. What do
we know now?</p>
<p>All analysis point towards a clear effect from <code>hours</code> on <code>grade</code>. This effect
was consistently visible in all of our models. But did we correctly identify
and estimate the effect of interest? Maybe. The problem is, we actually did not
approach the analysis correctly. In a real analysis we should <strong>absolutely</strong>
refrain from adding variables to our model that <em>could be</em> relevant until we are
satisfied or all available variables are bunched into one huge model. It was
fine to do this in this introduction to linear regression and for learning how
different types of variables can be used in a regression model. But in a real
project, we have to invest time to think about which variables to add because we
assume that they have a relevant effect based on theoretical assumptions about
the processes we are interested in.</p>
<p>So let us do this now and vow do make this our first step in all future
endeavors. While we do not have a clear theoretical basis, we can make clear
assumptions on the data generating process and draw these in a DAG.</p>
<pre><code>## Warning: package &#39;dagitty&#39; was built under R version 4.2.3</code></pre>
<p><img src="_main_files/figure-html/dag-1.png" width="672" /></p>
<p>XXX MAYBE NICEN IT UP XXX</p>
<p>Our central assumption, and the effect we want to identify and estimate, is the
direct effect from <code>hours</code> on <code>grade</code> in the bottom line. The more hours a
student invests, the better the grade should be. This is our variable of
interest and it has to be included in the model.</p>
<p>The assumed effect of <code>contact</code> is more complex. For one we assume that a more
in-depth contact with the lecturer will increase the grade directly. The
research question will be more focused, the student will know what is important
to a certain lecturer, common mistakes can be avoided if they are cleared up
beforehand and so on. But we will also assume that <code>contact</code> will have an effect
on <code>hours</code> in the sense that the hours invested can be used more efficiently if
an in-depth discussion has taken place. Instead of wasting time running into
problems that could have been avoided most of the invested time can actually go
into constructive work. This makes <code>contact</code> a confounder for <code>grade</code> and
<code>hours</code>. Tapping into the knowledge from the last session, now we know that we
also have to control for <code>contact</code> to measure the effect of <code>hours</code> correctly.</p>
<p>A student’s skill level will also have a direct effect on <code>grade</code>. As we do not
have a direct measure of skill in our data, we use <code>previous_grades</code> as a proxy
for skill level. <code>attendance</code> also has a direct effect on <code>grade</code> as students
who were present in the seminar will not only have learned the seminar’s
contents, but will also have a better understanding of what is expected in their
seminar papers. As neither skill level - or <code>previous_grades</code> - nor <code>attendance</code>
has any connection to <code>hours</code> we also should not control for them in our model.</p>
<p>That leaves us with <code>hours</code> and <code>contact</code> to be included in our linear
regression, if our goal is to accuarately identify and estimate the effect of
invested time on the final grade. So let us do this:</p>
<pre><code>## 
## Call:
## lm(formula = grade ~ hours_centered + contact, data = grades)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.85595 -0.74624 -0.02106  0.66648  2.50161 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       3.44352    0.10404  33.098  &lt; 2e-16 ***
## hours_centered   -0.04967    0.01052  -4.723 4.43e-06 ***
## contactE-Mail    -0.46482    0.16785  -2.769  0.00616 ** 
## contactIn Person -1.02804    0.15240  -6.746 1.67e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9305 on 196 degrees of freedom
## Multiple R-squared:  0.2643, Adjusted R-squared:  0.253 
## F-statistic: 23.47 on 3 and 196 DF,  p-value: 5.072e-13</code></pre>
<p>This is our estimate. Each hour invested beyond the mean of <span class="math inline">\(40.33\)</span> hours
changes the grade by about <span class="math inline">\(-0.05\)</span> points. This supports our hypotheses and we
can conclude, that investing more hours into writing a seminar paper actually
is a worthwhile investment.</p>
<p>But remember: This is correct as long as our DAG is drawn correctly. This is
always debatable. Maybe we should assume an effect from skill level on <code>hours</code>.
The higher the skill level the more efficiently the available time can be used.
For this example we know the DAG is correct, because we have simulated the data
exactly in this way. For real world applications we never know if our DAG is
correct. All we can - and have to - do is base it on thorough thought,
theoretical work and sound arguments.</p>
<p>This all is true <em>if</em> our goal is to estimate an effect of interest as precisely
as possible. But as we have alluded to in the introduction to this session we
could also use modelling with a different goal, i.e. predicting a grade as
accurately as possible. For this task, the model which only includes <code>hours</code> and
<code>contact</code> will not do the best job. From our DAG we know that <code>attendance</code> and
<code>previous_grade</code> should have an effect on <code>grade</code>, as we have also seen in our
models. For this task the full model including all these variables will produce
better estimates. We will return to this in a later session, but for now we
should remember that we have to know our task because the task dictates which is
the best model to use.</p>
</div>
<div id="maybes" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Maybes<a href="lin-t.html#maybes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>maybe talk about std. errors + p-values -&gt; or next week</p></li>
<li><p>Introduce R^2 and adj here</p></li>
<li><p>Mediation</p></li>
<li><p>maybe theory into DAG session and example into application</p></li>
<li><p>Interactions</p>
<ul>
<li>maybe introduce here and apply next session</li>
<li>maybe push it all into next session</li>
<li>or leave out completely</li>
</ul></li>
<li><p>Multiple outcomes</p></li>
<li><p>maybe leave out</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="eda-2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lin-a.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/04-Linear-Regression-theory.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
